### ISSUE TITLE
GPU used for training ?

### ISSUE THREAD

**Issue by bcba25** [deepcam-cn/Face-Anti-spoofing.pytorch#5]
What is graphic card you used for training ? I do have RTX2060 SUPER and seems like its not enough :(
I do receive the following:

RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 8.00 GiB total capacity; 5.92 GiB already allocated; 107.97 MiB free; 171.50 KiB cached)

**Comment by bcba25** [comment]
Alright the issue is solved by decreasing the batch size, but still just curious what are you using for training ? :)

**Comment by liurs1990** [comment]
I used RTX1070 to train the net.
